[project]
name = 'Decentralized-Digital-Identity-Lifecycle-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.attribute-management]
path = 'contracts/attribute-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.audit-trail]
path = 'contracts/audit-trail.clar'
clarity_version = 2
epoch = 2.5

[contracts.credential-revocation]
path = 'contracts/credential-revocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.identity-provider]
path = 'contracts/identity-provider.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
